const api = require('termux')

if (!api.hasTermux) process.exit(1)

api.vibrate()
   .duration(1000)
   .run()
api.toast('test toast')
.text('test toast')
.transient(5500)
.run()
api.dialog('test dialog')
.title('title')
.run()
api.notification('notification')
.content('content')
.id(2014)
.title('test ti')
.url('http://fddcn.cn')
.run()